### ISSUE TITLE
Use SemVer & tagged releases

### ISSUE THREAD

**Issue by colinodell** [stikmanw/silex-newrelic#10]
I'd like to propose using [Semantic Versioning](http://semver.org/) and tagged releases.  Some changes (like #9) would break existing integrations relying on the `dev-master` "version" thus causing headaches for end users.  Following SemVer would provide a reliable, meaningful versioning scheme to prevent these kinds of issues.

**Comment by stikmanw** [comment]
2 versions added v0.1.0 and v1.0.0
